name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: "Features"
    labels:
      - feature
      - enhancement
  - title: "Bug Fixes"
    labels:
      - bug
      - fix
  - title: "Maintenance"
    labels:
      - chore
      - cleanup
  - title: "Breaking Changes"
    labels:
      - breaking-change

change-template: "- $TITLE (#$NUMBER)"

exclude-labels:
  - skip-changelog

template: |
  ## What's New

  $CHANGES
